// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYKtfH6ncwbrYjkkX2tKFuiK1E_iV_yA',
    appId: '1:939211883831:android:58518fd6431afa975ac6b2',
    messagingSenderId: '939211883831',
    projectId: 'my-academic-appointment',
    storageBucket: 'my-academic-appointment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBthSu7EHdhTTAP0UL7R3TCCGl2xcZOI0E',
    appId: '1:939211883831:ios:d99145f2c3e8bac55ac6b2',
    messagingSenderId: '939211883831',
    projectId: 'my-academic-appointment',
    storageBucket: 'my-academic-appointment.firebasestorage.app',
    iosBundleId: 'com.example.scholappoinment934074496',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCljXBlN1yVXWqAgvBPTG7ZPIRi4kZb9Lw',
    appId: '1:939211883831:web:0e40dd346a9406d45ac6b2',
    messagingSenderId: '939211883831',
    projectId: 'my-academic-appointment',
    authDomain: 'my-academic-appointment.firebaseapp.com',
    databaseURL: 'https://my-academic-appointment-default-rtdb.firebaseio.com',
    storageBucket: 'my-academic-appointment.firebasestorage.app',
    measurementId: 'G-R176ZYEG2T',
  );
}
