name: scholappoinment_934074496
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # For integrating to firebase  
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_database: ^11.3.2
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  cloud_firestore: ^5.6.3
  cached_network_image: ^3.4.1
  http: ^1.3.0
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # sflutter_launcher_icons: "^0.14.3"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "images/Logo.ico"
#   min_sdk_android: 21
#   web:
#     generate: true
#     image_path: "path/to/image.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "path/to/image.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/splash_screen.png
